# Copyright (c) Abstract Machines
# SPDX-License-Identifier: Apache-2.0

with-expecter: true
filename: "{{.InterfaceName}}.go"
outpkg: "mocks"
boilerplate-file: "./tools/config/boilerplate.txt"
packages:
  github.com/absmach/magistrala:
    interfaces:
      ThingsServiceClient:
        config:
          dir: "./things/mocks"
          mockname: "ThingsServiceClient"
          filename: "things_client.go"
      DomainsServiceClient:
        config:
          dir: "./auth/mocks"
          mockname: "DomainsServiceClient"
          filename: "domains_client.go"
